name: Update APMC Rates Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC (11:30 AM IST)
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run fetchRates script
        run: node fetchRates.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
